/**
 * Lista de marcas de carros baseada no enum CarBrand do backend
 */
export const CAR_BRANDS = [
  { value: 'VOLKSWAGEN', label: 'Volkswagen' },
  { value: 'FIAT', label: 'Fiat' },
  { value: 'FORD', label: 'Ford' },
  { value: 'CHEVROLET', label: 'Chevrolet' },
  { value: 'RENAULT', label: 'Renault' },
  { value: 'TOYOTA', label: 'Toyota' },
  { value: 'HONDA', label: 'Honda' },
  { value: 'HYUNDAI', label: 'Hyundai' },
  { value: 'NISSAN', label: 'Nissan' },
  { value: 'PEUGEOT', label: 'Peugeot' },
  { value: 'CITROEN', label: 'Citroën' },
  { value: 'MERCEDES_BENZ', label: 'Mercedes-Benz' },
  { value: 'BMW', label: 'BMW' },
  { value: 'AUDI', label: 'Audi' },
  { value: 'VOLVO', label: 'Volvo' },
  { value: 'JEEP', label: 'Jeep' },
  { value: 'MITSUBISHI', label: 'Mitsubishi' },
  { value: 'KIA', label: 'Kia' },
  { value: 'SUZUKI', label: 'Suzuki' },
  { value: 'MAZDA', label: 'Mazda' },
  { value: 'SUBARU', label: 'Subaru' },
  { value: 'LAND_ROVER', label: 'Land Rover' },
  { value: 'JAGUAR', label: 'Jaguar' },
  { value: 'PORSCHE', label: 'Porsche' },
  { value: 'FERRARI', label: 'Ferrari' },
  { value: 'LAMBORGHINI', label: 'Lamborghini' },
  { value: 'MASERATI', label: 'Maserati' },
  { value: 'ALFA_ROMEO', label: 'Alfa Romeo' },
  { value: 'MINI', label: 'Mini' },
  { value: 'SMART', label: 'Smart' },
  { value: 'RAM', label: 'RAM' },
  { value: 'DODGE', label: 'Dodge' },
  { value: 'CHRYSLER', label: 'Chrysler' },
  { value: 'CADILLAC', label: 'Cadillac' },
  { value: 'LINCOLN', label: 'Lincoln' },
  { value: 'INFINITI', label: 'Infiniti' },
  { value: 'ACURA', label: 'Acura' },
  { value: 'LEXUS', label: 'Lexus' },
  { value: 'TESLA', label: 'Tesla' },
  { value: 'BYD', label: 'BYD' },
  { value: 'CHERY', label: 'Chery' },
  { value: 'JAC', label: 'JAC' },
  { value: 'LIFAN', label: 'Lifan' },
  { value: 'TAC', label: 'TAC' },
  { value: 'GREAT_WALL', label: 'Great Wall' },
  { value: 'CAOA_CHERY', label: 'CAOA Chery' },
  { value: 'IVECO', label: 'Iveco' },
  { value: 'SCANIA', label: 'Scania' },
  { value: 'MAN', label: 'MAN' },
  { value: 'MERCEDES_BENZ_TRUCKS', label: 'Mercedes-Benz Trucks' },
] as const

